DROP TABLE IF EXISTS `vehicle` CASCADE;
CREATE TABLE `vehicle` (
	`id` INTEGER UNIQUE PRIMARY KEY AUTO_INCREMENT, 
	`vrm` VARCHAR(255),
	`mileage` DOUBLE,
	`description` VARCHAR(255), 
	`cost` DOUBLE 
	
);